spring:
  application:
    name: finances-agent
  ai:
    ollama:
      base-url: http://llm:11434
      chat:
#        model: mistral
        model: qwen2.5:7b
  kafka:
    bootstrap-servers: kafka.lavacro.net:9092
    consumer:
      group-id: 'finances-agent-CG'
      auto-offset-reset: latest
      max-poll-records: 500
      enable-auto-commit: true
      client-id: 'finances-agent-consumer'
      fetch-min-size: 4096
      fetch-max-wait: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
